"""
Podcast RSS 2.0 Feed Generator with iTunes & Apple Podcasts extensions.
Formats audio enclosures, show notes, chapter markers, and artwork for Overcast.
"""
import os
import re
import json
from datetime import datetime, timezone
from email.utils import format_datetime, parsedate_to_datetime
from xml.etree import ElementTree as ET
from xml.dom import minidom
from typing import List, Dict, Any, Optional

def format_duration(seconds: Optional[int]) -> str:
    """Formats duration in seconds to HH:MM:SS or MM:SS."""
    if not seconds:
        return "00:00"
    m, s = divmod(int(seconds), 60)
    h, m = divmod(m, 60)
    if h > 0:
        return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def parse_date_to_datetime(val: Any) -> datetime:
    """Parses various date/time formats into an aware UTC datetime object."""
    if not val:
        return datetime.now(timezone.utc)
    if isinstance(val, (int, float)):
        try:
            return datetime.fromtimestamp(val, tz=timezone.utc)
        except Exception:
            return datetime.now(timezone.utc)
    if isinstance(val, datetime):
        return val if val.tzinfo else val.replace(tzinfo=timezone.utc)
    val_str = str(val).strip()
    if not val_str:
        return datetime.now(timezone.utc)
    # ISO 8601
    try:
        if "T" in val_str:
            dt = datetime.fromisoformat(val_str.replace("Z", "+00:00"))
            return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)
    except Exception:
        pass
    # YYYY-MM-DD HH:MM:SS
    try:
        dt = datetime.strptime(val_str, "%Y-%m-%d %H:%M:%S")
        return dt.replace(tzinfo=timezone.utc)
    except Exception:
        pass
    # YYYY-MM-DD
    try:
        dt = datetime.strptime(val_str, "%Y-%m-%d")
        return dt.replace(tzinfo=timezone.utc)
    except Exception:
        pass
    # RFC 2822 / 822 format
    try:
        dt = parsedate_to_datetime(val_str)
        return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)
    except Exception:
        pass
    return datetime.now(timezone.utc)

def parse_to_rfc822(date_str: Optional[str]) -> str:
    """Converts any date string or timestamp to RFC 822 format."""
    dt = parse_date_to_datetime(date_str)
    return format_datetime(dt)

class FeedGenerator:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.public_base_url = config.get("public_base_url", "http://localhost:8080").rstrip("/")
        self.feed_title = config.get("feed_title", "The Dice Tower (TowerCast)")
        self.feed_desc = config.get("feed_description", "Private podcast feed generated by TowerCast.")
        self.feed_author = config.get("feed_author", "The Dice Tower")
        self.feed_image = config.get("feed_image_url", "")
        self.audio_format = config.get("audio_format", "m4a")

    def _get_mime_type(self, filename: str) -> str:
        if filename.endswith(".m4a"):
            return "audio/mp4"
        elif filename.endswith(".mp3"):
            return "audio/mpeg"
        elif filename.endswith(".aac"):
            return "audio/aac"
        return "audio/mp4"

    def _format_show_notes_with_chapters(self, description: str, chapters_json: Optional[str]) -> str:
        """Appends formatted chapter timestamps into show notes for podcast players."""
        text = description or ""
        if not chapters_json:
            return text

        try:
            chapters = json.loads(chapters_json) if isinstance(chapters_json, str) else chapters_json
            if chapters and isinstance(chapters, list):
                chapter_lines = ["\n\n--- Chapters ---"]
                for ch in chapters:
                    start_sec = int(ch.get("start_time", 0))
                    title = ch.get("title", "Chapter")
                    chapter_lines.append(f"{format_duration(start_sec)} - {title}")
                text += "\n".join(chapter_lines)
        except Exception:
            pass
        return text

    def generate_feed_xml(self, episodes: List[Dict[str, Any]]) -> str:
        """
        Generates complete RSS 2.0 XML string.
        """
        rss = ET.Element("rss", {
            "version": "2.0",
            "xmlns:itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd",
            "xmlns:content": "http://purl.org/rss/1.0/modules/content/",
            "xmlns:atom": "http://www.w3.org/2005/Atom"
        })

        channel = ET.SubElement(rss, "channel")

        # Atom self link
        atom_link = ET.SubElement(channel, "atom:link", {
            "href": f"{self.public_base_url}/feed.xml",
            "rel": "self",
            "type": "application/rss+xml"
        })

        ET.SubElement(channel, "title").text = self.feed_title
        ET.SubElement(channel, "link").text = self.public_base_url
        ET.SubElement(channel, "description").text = self.feed_desc
        ET.SubElement(channel, "language").text = "en-us"
        ET.SubElement(channel, "lastBuildDate").text = format_datetime(datetime.now(timezone.utc))

        # iTunes channel tags
        ET.SubElement(channel, "itunes:author").text = self.feed_author
        ET.SubElement(channel, "itunes:summary").text = self.feed_desc
        ET.SubElement(channel, "itunes:explicit").text = "false"

        category = ET.SubElement(channel, "itunes:category", {"text": "Leisure"})
        ET.SubElement(category, "itunes:category", {"text": "Games"})

        if self.feed_image:
            ET.SubElement(channel, "itunes:image", {"href": self.feed_image})
            img = ET.SubElement(channel, "image")
            ET.SubElement(img, "url").text = self.feed_image
            ET.SubElement(img, "title").text = self.feed_title
            ET.SubElement(img, "link").text = self.public_base_url

        # Episode items (strictly sorted reverse-chronological by publication date)
        sorted_episodes = sorted(
            episodes,
            key=lambda ep: parse_date_to_datetime(ep.get("published_at")),
            reverse=True
        )
        for ep in sorted_episodes:
            self._add_episode_item(channel, ep, use_full_audio_url=False)

        xml_bytes = ET.tostring(rss, encoding="utf-8")
        parsed = minidom.parseString(xml_bytes)
        return parsed.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")

    def generate_feed_xml_with_full_urls(self, episodes: List[Dict[str, Any]]) -> str:
        """
        Variant for the GitHub CI builder. Episodes carry an 'audio_url' field
        (GitHub Releases CDN URL) that is used directly as the enclosure URL,
        bypassing the local public_base_url + filename construction.
        """
        rss = ET.Element("rss", {
            "version": "2.0",
            "xmlns:itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd",
            "xmlns:content": "http://purl.org/rss/1.0/modules/content/",
            "xmlns:atom": "http://www.w3.org/2005/Atom",
        })
        channel = ET.SubElement(rss, "channel")

        ET.SubElement(channel, "atom:link", {
            "href": f"{self.public_base_url}/feed.xml",
            "rel": "self",
            "type": "application/rss+xml",
        })
        ET.SubElement(channel, "title").text = self.feed_title
        ET.SubElement(channel, "link").text = self.public_base_url
        ET.SubElement(channel, "description").text = self.feed_desc
        ET.SubElement(channel, "language").text = "en-us"
        ET.SubElement(channel, "lastBuildDate").text = format_datetime(datetime.now(timezone.utc))
        ET.SubElement(channel, "itunes:author").text = self.feed_author
        ET.SubElement(channel, "itunes:summary").text = self.feed_desc
        ET.SubElement(channel, "itunes:explicit").text = "false"

        category = ET.SubElement(channel, "itunes:category", {"text": "Leisure"})
        ET.SubElement(category, "itunes:category", {"text": "Games"})

        if self.feed_image:
            ET.SubElement(channel, "itunes:image", {"href": self.feed_image})
            img = ET.SubElement(channel, "image")
            ET.SubElement(img, "url").text = self.feed_image
            ET.SubElement(img, "title").text = self.feed_title
            ET.SubElement(img, "link").text = self.public_base_url

        # Episode items (strictly sorted reverse-chronological by publication date)
        sorted_episodes = sorted(
            episodes,
            key=lambda ep: parse_date_to_datetime(ep.get("published_at")),
            reverse=True
        )
        for ep in sorted_episodes:
            self._add_episode_item(channel, ep, use_full_audio_url=True)

        xml_bytes = ET.tostring(rss, encoding="utf-8")
        parsed = minidom.parseString(xml_bytes)
        return parsed.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")

    def _add_episode_item(self, channel: Any, ep: Dict[str, Any],
                          use_full_audio_url: bool = False):
        """Shared helper that appends an <item> element to a channel."""
        # Determine audio URL
        if use_full_audio_url and ep.get("audio_url"):
            audio_url = ep["audio_url"]
            mime_type = self._get_mime_type(audio_url)
        else:
            audio_fn = ep.get("audio_filename")
            if not audio_fn:
                return
            audio_url = f"{self.public_base_url}/audio/{audio_fn}"
            mime_type = self._get_mime_type(audio_fn)

        file_size = str(ep.get("file_size") or 0)

        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = ep.get("title", "Untitled Episode")
        ET.SubElement(item, "guid", {"isPermaLink": "false"}).text = f"towercast-{ep.get('id')}"
        ET.SubElement(item, "pubDate").text = parse_to_rfc822(ep.get("published_at"))
        ET.SubElement(item, "enclosure", {"url": audio_url, "length": file_size, "type": mime_type})

        full_notes = self._format_show_notes_with_chapters(ep.get("description", ""), ep.get("chapters_json"))
        ET.SubElement(item, "description").text = full_notes
        content_encoded = ET.SubElement(item, "content:encoded")
        html_desc = "<p>" + full_notes.replace("\n\n", "</p><p>").replace("\n", "<br/>") + "</p>"
        content_encoded.text = html_desc

        duration_sec = ep.get("duration")
        if duration_sec:
            ET.SubElement(item, "itunes:duration").text = format_duration(duration_sec)

        ET.SubElement(item, "itunes:author").text = self.feed_author
        ET.SubElement(item, "itunes:explicit").text = "false"

        thumb_url = ep.get("thumbnail_url")
        if thumb_url:
            ET.SubElement(item, "itunes:image", {"href": thumb_url})
        elif self.feed_image:
            ET.SubElement(item, "itunes:image", {"href": self.feed_image})
